apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shreybatra/sample-frontend
          ports:
            - containerPort: 5173
          env:
            - name: VITE_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VITE_BACKEND_URL
          command: ["npm", "run", "preview"]
          args: ["--", "--host", "0.0.0.0"]